### PR TITLE
update rubocop to 0.76

### PR DESCRIPTION
**Pull request by mtmail**
Update rubocop from 0.49 to 0.73. A couple of cops renamed

### CODE REVIEW

**Comment by mtmail** [comment]
Travis-CI test failures because travis no longer support Ruby 2.3 and below. See https://github.com/kontena/kong-client-ruby/pull/40

**Comment by nevalla** [comment]
Hi #40 is now merged to master. Please rebase.

**Comment by mtmail** [comment]
rebased now

**Comment by mtmail** [comment]
Included the approved https://github.com/kontena/kong-client-ruby/pull/40 now and tests pass again.

**Comment by nevalla** [comment]
Yeah thanks and sorry. Hit the wrong button on #40 🤦‍♂

**Pull request merged**
