### PR TITLE
add methods to kong api base attributes

### PR DESCRIPTION
**Pull request by gabrie30**

### CODE REVIEW

**Comment by nevalla** [comment]
Cool! Thanks for contributing 🍻

**Comment by gabrie30** [comment]
Thanks for the quick turn-around!

**Comment by gabrie30** [comment]
Any chance you'll be able to cut a new release?

**Comment by nevalla** [comment]
Yes. Will be out very soon.

**Comment by gabrie30** [comment]
🎉 Thanks!

**Comment by nevalla** [comment]
Version 0.3.1 is out now

**Pull request merged**
