### PR TITLE
Allow to properly set a custom api_url

### PR DESCRIPTION
**Pull request by Tuxii**
Potential fix for Issue #3

### CODE REVIEW

**Comment by nevalla** [comment]
Thanks! I'll check this shortly and verify it before merging.

**Comment by Tuxii** [comment]
Hello,

Any updates on this ? 

I'm still using my fork for now but this gem could use some more PR to add new features like ACL support or fix unwanted behavior like https://github.com/kontena/kong-client-ruby/issues/5

At my company, we could provide those PR but we need to make sure it could be merged shortly, or else we would better create a client of our own.

**Comment by nevalla** [comment]
Sorry for delay. Looks definitely good! Thanks for contributing!

**Comment by Tuxii** [comment]
Glad to see it merged, thank you :)

**Pull request merged**
